# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 737)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("border-image: url(:/Map_pictures/main_map/Full_map.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 200, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("border-image: url(:/newPrefix/main_map/Full_map.png);")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Btn_START = QtWidgets.QPushButton(self.widget)
        self.Btn_START.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_START.setFont(font)
        self.Btn_START.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_START.setStyleSheet("border-image: url(:/symbols/symbols/buttons_shatered_5.png);")
        self.Btn_START.setObjectName("Btn_START")
        self.verticalLayout.addWidget(self.Btn_START)
        self.Btn_EDIT = QtWidgets.QPushButton(self.widget)
        self.Btn_EDIT.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_EDIT.setFont(font)
        self.Btn_EDIT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_EDIT.setStyleSheet("border-image: url(:/symbols/symbols/buttons_shatered_1.png);")
        self.Btn_EDIT.setObjectName("Btn_EDIT")
        self.verticalLayout.addWidget(self.Btn_EDIT)
        self.Btn_SETTINGS = QtWidgets.QPushButton(self.widget)
        self.Btn_SETTINGS.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Btn_SETTINGS.setFont(font)
        self.Btn_SETTINGS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_SETTINGS.setStyleSheet("border-image: url(:/symbols/symbols/buttons_normal_3.png);")
        self.Btn_SETTINGS.setObjectName("Btn_SETTINGS")
        self.verticalLayout.addWidget(self.Btn_SETTINGS)
        self.Btn_EXIT = QtWidgets.QPushButton(self.widget)
        self.Btn_EXIT.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Btn_EXIT.setFont(font)
        self.Btn_EXIT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_EXIT.setStyleSheet("border-image: url(:/symbols/symbols/buttons_shatered_5.png);")
        self.Btn_EXIT.setObjectName("Btn_EXIT")
        self.verticalLayout.addWidget(self.Btn_EXIT)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_START.setText(_translate("MainWindow", "START"))
        self.Btn_EDIT.setText(_translate("MainWindow", "EDIT"))
        self.Btn_SETTINGS.setText(_translate("MainWindow", "SETTINGS"))
        self.Btn_EXIT.setText(_translate("MainWindow", "EXIT"))


import resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Menu_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
